/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import model from "./MER_static.glb";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(model);
  return (
    <>
      {/* <spotLight position={[0, 5, 0]} intensity={4} /> */}
      {/* <pointLight position={[10, 10, 0]} intensity={4} />
      <ambientLight intensity={12} /> */}

      {/* <directionalLight intensity={12} position={[0, 5, 0]} /> */}
      {/* <pointLight position={[0, 5, 0]} intensity={4} /> */}
      {/* <pointLight position={[0, 20, 0]} intensity={4} decay={2} /> */}
      {/* <pointLight position={[5, 5, 0]} intensity={4} />
      <pointLight position={[0, 5, 5]} intensity={4} /> */}
      {/* <ambientLight intensity={5} /> */}
      <group ref={group} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000.geometry}
          material={materials.tex_panels_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_1.geometry}
          material={materials.tex_panels2_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_2.geometry}
          material={materials.tex_instruments}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_3.geometry}
          material={materials.tex_body_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_4.geometry}
          material={materials.tex_suspension_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_5.geometry}
          material={materials.Silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_6.geometry}
          material={materials.tex_mast}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_7.geometry}
          material={materials.foil_silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_8.geometry}
          material={materials.tex_arm}
        />
      </group>
    </>
  );
}

useGLTF.preload(model);
