/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import model from "./insight.glb";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(model);
  return (
    <group ref={group} {...props} dispose={null} scale={[0.5, 0.5, 0.5]}>
      <group position={[0, 0.66, -0.13]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_1.geometry}
          material={materials.deck}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_2.geometry}
          material={materials.InSIGHT_AO_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_3.geometry}
          material={materials["foil silver"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_4.geometry}
          material={materials.InSIGHT_AO_05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_5.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_6.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_7.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_8.geometry}
          material={materials.InSIGHT_AO_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_9.geometry}
          material={materials.InSIGHT_AO_06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_10.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_10.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_11.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_11.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_12.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_12.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_13.geometry}
          material={nodes.Lander_Deployed_Simplified_coarse1043_13.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_14.geometry}
          material={materials.foil_silver_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lander_Deployed_Simplified_coarse1043_15.geometry}
          material={materials.InSIGHT_AO_07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.arm_01.geometry}
          material={nodes.arm_01.material}
          position={[-0.29, 0.42, 0.92]}
          rotation={[-Math.PI, 0.36, -Math.PI]}
        >
          <group position={[0.02, 0.05, -0.04]} rotation={[-2.74, -0.34, 1.71]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube287.geometry}
              material={nodes.Cube287.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube287_1.geometry}
              material={nodes.Cube287_1.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube287_2.geometry}
              material={nodes.Cube287_2.material}
            />
            <group
              position={[-0.8, -0.1, 0.59]}
              rotation={[-3.14, 1.46, -3.14]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube286.geometry}
                material={nodes.Cube286.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube286_1.geometry}
                material={nodes.Cube286_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube286_2.geometry}
                material={nodes.Cube286_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.grapple.geometry}
                material={nodes.grapple.material}
                position={[-0.36, -0.08, 0.8]}
                rotation={[3.11, -1.04, -0.06]}
              >
                <group
                  position={[-0.16, -0.02, -0.19]}
                  rotation={[-3.14, -0.3, 0]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube285.geometry}
                    material={nodes.Cube285.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube285_1.geometry}
                    material={nodes.Cube285_1.material}
                  />
                </group>
                <group
                  position={[-0.17, -0.04, -0.18]}
                  rotation={[2.59, -0.55, 0.91]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube284.geometry}
                    material={nodes.Cube284.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube284_1.geometry}
                    material={nodes.Cube284_1.material}
                  />
                </group>
                <group
                  position={[-0.18, -0.03, -0.16]}
                  rotation={[2.48, -1.1, 1.96]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube283.geometry}
                    material={nodes.Cube283.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube283_1.geometry}
                    material={nodes.Cube283_1.material}
                  />
                </group>
                <group
                  position={[-0.18, -0.01, -0.16]}
                  rotation={[-0.03, 0.76, -0.61]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube282.geometry}
                    material={nodes.Cube282.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube282_1.geometry}
                    material={nodes.Cube282_1.material}
                  />
                </group>
                <group
                  position={[-0.17, 0, -0.18]}
                  rotation={[-2.59, -0.55, -0.91]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube281.geometry}
                    material={nodes.Cube281.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube281_1.geometry}
                    material={nodes.Cube281_1.material}
                  />
                </group>
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube019.geometry}
                material={nodes.Cube019.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube019_1.geometry}
                material={nodes.Cube019_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.knob.geometry}
                material={nodes.knob.material}
                position={[-0.16, -0.04, 0.4]}
                rotation={[-2.76, -1.14, 1.88]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.lens_cap_IDC.geometry}
                material={nodes.lens_cap_IDC.material}
                position={[0.01, -0.06, 0.35]}
                rotation={[0, -0.77, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.shovel.geometry}
                material={nodes.shovel.material}
                position={[-0.36, -0.04, 0.8]}
                rotation={[-3.14, -1.32, 0]}
              />
            </group>
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.panel_l_rod.geometry}
          material={nodes.panel_l_rod.material}
          position={[-0.85, 0.35, -0.42]}
        />
        <group position={[-0.85, 0.34, -0.44]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lander_Deployed_Simplified_coarse000.geometry}
            material={nodes.Lander_Deployed_Simplified_coarse000.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lander_Deployed_Simplified_coarse000_1.geometry}
            material={nodes.Lander_Deployed_Simplified_coarse000_1.material}
          />
          <group
            position={[-0.5, 0, -0.02]}
            rotation={[-0.79, -1.51, -2.31]}
            scale={[0.03, 0.03, 0.03]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007.geometry}
              material={nodes.Cube007.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_1.geometry}
              material={nodes.Cube007_1.material}
            />
          </group>
          <group position={[-1.1, -0.02, 0.01]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lander_Deployed_Simplified_coarse005.geometry}
              material={nodes.Lander_Deployed_Simplified_coarse005.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lander_Deployed_Simplified_coarse005_1.geometry}
              material={nodes.Lander_Deployed_Simplified_coarse005_1.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.panel_l019.geometry}
              material={nodes.panel_l019.material}
              position={[0, 0.08, 0.02]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={nodes.Cube001.material}
                position={[-0.49, -0.05, 0.01]}
                rotation={[-1.95, 1.52, 0.38]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube047.geometry}
                material={nodes.Cube047.material}
                position={[-0.59, -0.05, 0.01]}
                rotation={[1.2, -1.52, -0.37]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube048.geometry}
                material={nodes.Cube048.material}
                position={[-0.49, -0.05, 0.01]}
                rotation={[-1.95, 1.52, 0.38]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.panel_l020.geometry}
                material={nodes.panel_l020.material}
                position={[0, -0.04, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube049.geometry}
                  material={nodes.Cube049.material}
                  position={[-0.47, -0.01, 0.35]}
                  rotation={[0.07, -0.93, -1.51]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube050.geometry}
                  material={nodes.Cube050.material}
                  position={[-0.41, -0.01, 0.31]}
                  rotation={[-3.07, 0.93, 1.52]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.panel_l021.geometry}
                  material={nodes.panel_l021.material}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube051.geometry}
                    material={nodes.Cube051.material}
                    position={[-0.18, -0.01, 0.55]}
                    rotation={[0.05, -0.31, -1.55]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube052_2.geometry}
                    material={nodes.Cube052_2.material}
                    position={[-0.15, -0.01, 0.47]}
                    rotation={[-3.1, 0.31, 1.56]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.panel_l031.geometry}
                    material={nodes.panel_l031.material}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube056.geometry}
                      material={nodes.Cube056.material}
                      position={[0.2, -0.02, 0.62]}
                      rotation={[0.05, 0.32, -1.58]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube057.geometry}
                      material={nodes.Cube057.material}
                      position={[0.18, -0.01, 0.55]}
                      rotation={[-3.09, -0.32, 1.59]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.panel_l032.geometry}
                      material={nodes.panel_l032.material}
                    >
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube054.geometry}
                        material={nodes.Cube054.material}
                        position={[0.49, -0.01, 0.35]}
                        rotation={[-3.07, -0.94, 1.64]}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube055.geometry}
                        material={nodes.Cube055.material}
                        position={[0.54, -0.02, 0.39]}
                        rotation={[0.07, 0.94, -1.63]}
                      />
                      <group position={[0, -0.09, 0.01]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Lander_Deployed_Simplified_coarse032.geometry
                          }
                          material={
                            nodes.Lander_Deployed_Simplified_coarse032.material
                          }
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Lander_Deployed_Simplified_coarse032_1
                              .geometry
                          }
                          material={
                            nodes.Lander_Deployed_Simplified_coarse032_1
                              .material
                          }
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube053.geometry}
                          material={nodes.Cube053.material}
                          position={[0.6, 0.08, 0.01]}
                          rotation={[1.38, 1.53, -2.94]}
                        />
                      </group>
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.panel_l034.geometry}
                material={nodes.panel_l034.material}
                position={[0, -0.04, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube064.geometry}
                  material={nodes.Cube064.material}
                  position={[-0.48, -0.01, -0.33]}
                  rotation={[3.06, -0.96, 1.51]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube065.geometry}
                  material={nodes.Cube065.material}
                  position={[-0.42, -0.01, -0.29]}
                  rotation={[-0.08, 0.96, -1.5]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.panel_l035.geometry}
                  material={nodes.panel_l035.material}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube062.geometry}
                    material={nodes.Cube062.material}
                    position={[-0.19, -0.01, -0.55]}
                    rotation={[3.09, -0.34, 1.56]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube063.geometry}
                    material={nodes.Cube063.material}
                    position={[-0.17, -0.01, -0.48]}
                    rotation={[-0.05, 0.34, -1.55]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.panel_l036.geometry}
                    material={nodes.panel_l036.material}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube060_1.geometry}
                      material={nodes.Cube060_1.material}
                      position={[0.16, -0.01, -0.56]}
                      rotation={[3.1, 0.28, 1.59]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube061_1.geometry}
                      material={nodes.Cube061_1.material}
                      position={[0.13, -0.01, -0.45]}
                      rotation={[-0.05, -0.28, -1.58]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.panel_l037.geometry}
                      material={nodes.panel_l037.material}
                    >
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube058.geometry}
                        material={nodes.Cube058.material}
                        position={[0.46, -0.01, -0.36]}
                        rotation={[-0.07, -0.9, -1.62]}
                      />
                      <group
                        position={[0.48, -0.01, -0.37]}
                        rotation={[3.07, 0.9, 1.68]}
                      >
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube069_1.geometry}
                          material={nodes.Cube069_1.material}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube069_2.geometry}
                          material={nodes.Cube069_2.material}
                        />
                      </group>
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.panel_r_rod.geometry}
          material={nodes.panel_r_rod.material}
          position={[0.85, 0.35, -0.42]}
        />
        <group position={[0.85, 0.34, -0.44]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube040.geometry}
            material={nodes.Cube040.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube040_1.geometry}
            material={nodes.Cube040_1.material}
          />
          <group position={[1.1, -0.03, 0.01]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube052.geometry}
              material={nodes.Cube052.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube052_1.geometry}
              material={nodes.Cube052_1.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube071.geometry}
              material={nodes.Cube071.material}
              position={[0, 0.09, 0.02]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002.geometry}
                material={nodes.Cube002.material}
                position={[0.59, -0.05, 0.01]}
                rotation={[-1.92, -1.52, -0.35]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube070.geometry}
                material={nodes.Cube070.material}
                position={[0, -0.06, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube069.geometry}
                  material={nodes.Cube069.material}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube068.geometry}
                    material={nodes.Cube068.material}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube067.geometry}
                      material={nodes.Cube067.material}
                    >
                      <group
                        position={[-0.44, 0, -0.34]}
                        rotation={[3.07, -0.9, -1.68]}
                      >
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube038.geometry}
                          material={nodes.Cube038.material}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube038_1.geometry}
                          material={nodes.Cube038_1.material}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube080.geometry}
                        material={nodes.Cube080.material}
                        position={[-0.5, 0, -0.39]}
                        rotation={[-0.07, 0.9, 1.62]}
                      />
                    </mesh>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube081.geometry}
                      material={nodes.Cube081.material}
                      position={[-0.14, 0.01, -0.47]}
                      rotation={[3.1, -0.28, -1.59]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube082.geometry}
                      material={nodes.Cube082.material}
                      position={[-0.16, 0, -0.56]}
                      rotation={[-0.05, 0.28, 1.58]}
                    />
                  </mesh>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube083.geometry}
                    material={nodes.Cube083.material}
                    position={[0.16, 0.01, -0.46]}
                    rotation={[3.09, 0.34, -1.56]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube084.geometry}
                    material={nodes.Cube084.material}
                    position={[0.2, 0, -0.55]}
                    rotation={[-0.05, -0.34, 1.55]}
                  />
                </mesh>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube085.geometry}
                  material={nodes.Cube085.material}
                  position={[0.34, 0.01, -0.24]}
                  rotation={[3.06, 0.96, -1.51]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube086.geometry}
                  material={nodes.Cube086.material}
                  position={[0.48, 0, -0.33]}
                  rotation={[-0.08, -0.96, 1.5]}
                />
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube072.geometry}
                material={nodes.Cube072.material}
                position={[0, -0.06, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube073.geometry}
                  material={nodes.Cube073.material}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube074_1.geometry}
                    material={nodes.Cube074_1.material}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube075_1.geometry}
                      material={nodes.Cube075_1.material}
                    >
                      <group position={[0.01, -0.03, 0.01]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube051_1.geometry}
                          material={nodes.Cube051_1.material}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube051_2.geometry}
                          material={nodes.Cube051_2.material}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube097.geometry}
                          material={nodes.Cube097.material}
                          position={[-0.61, 0.03, 0.01]}
                          rotation={[1.33, -1.53, 2.9]}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube095.geometry}
                        material={nodes.Cube095.material}
                        position={[-0.42, 0, 0.31]}
                        rotation={[0.07, -0.94, 1.63]}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube096.geometry}
                        material={nodes.Cube096.material}
                        position={[-0.51, 0, 0.36]}
                        rotation={[-3.07, 0.94, -1.63]}
                      />
                    </mesh>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube093.geometry}
                      material={nodes.Cube093.material}
                      position={[-0.16, 0, 0.51]}
                      rotation={[0.05, -0.31, 1.58]}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube094.geometry}
                      material={nodes.Cube094.material}
                      position={[-0.19, 0, 0.57]}
                      rotation={[-3.09, 0.31, -1.59]}
                    />
                  </mesh>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube091.geometry}
                    material={nodes.Cube091.material}
                    position={[0.16, 0, 0.49]}
                    rotation={[0.05, 0.31, 1.55]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube092.geometry}
                    material={nodes.Cube092.material}
                    position={[0.17, 0, 0.56]}
                    rotation={[-3.1, -0.31, -1.56]}
                  />
                </mesh>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube089.geometry}
                  material={nodes.Cube089.material}
                  position={[0.43, 0, 0.32]}
                  rotation={[0.07, 0.93, 1.51]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube090.geometry}
                  material={nodes.Cube090.material}
                  position={[0.49, 0, 0.37]}
                  rotation={[-3.07, -0.93, -1.51]}
                />
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube087.geometry}
                material={nodes.Cube087.material}
                position={[0.48, -0.05, 0]}
                rotation={[1.22, 1.52, 0.34]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube088.geometry}
                material={nodes.Cube088.material}
                position={[0.59, -0.05, 0.01]}
                rotation={[-1.92, -1.52, -0.35]}
              />
            </mesh>
          </group>
          <group position={[0.5, 0, -0.02]} rotation={[-0.79, 1.51, 2.31]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube039.geometry}
              material={nodes.Cube039.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube039_1.geometry}
              material={nodes.Cube039_1.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(model);
