/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import model from "./curiosity.glb";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(model);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.06, 0.25, 1.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials.wheels}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.tex_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_2.geometry}
          material={materials.tex_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_3.geometry}
          material={materials.parts_AO}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_4.geometry}
          material={materials.tex_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_5.geometry}
          material={materials.tex_05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_6.geometry}
          material={materials.tex_04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_7.geometry}
          material={materials.tex_03a}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_8.geometry}
          material={materials.internals}
        />
      </group>
    </group>
  );
}

useGLTF.preload(model);
